### ISSUE TITLE
Cache generated template to reduce API calls

### ISSUE THREAD

**Issue by codyjames** [superbigco/craft-mjml#15]
### Is your feature request related to a problem? Please describe.
I'm using this with Craft Campaign. However, in their docs they state:
> The MJML plugin provides you with Twig tags to render email templates. Using the MJML API to render email templates will significantly slow down the sending process due to latency, therefore we highly recommend using MJML only to generate the markup for your templates. 

### Describe the solution you would like
Is there a way to work around this? Perhaps by caching the generated template (but not caching any craft/campaign templating code) so it doesn't need to re-run for each email sent out.

### Additional context
We'll be sending emails to tens of thousands of users so performance and speed are pretty important.

**Comment by sjelfull** [comment]
@codyjames I think this is a good idea, but I don't have time at the moment. If you have budget, feel free to get in touch with me at contact@superbig.co for consulting.

**Comment by sjelfull** [comment]
This is now out in 1.0.6.
