### ISSUE TITLE
Request: Update for Craft 4

### ISSUE THREAD

**Issue by thupsi** [superbigco/craft-mjml#17]
Hello! Are there any plans to update the plugin for Craft 4?

**Comment by adrienpicard** [comment]
+1 would be great to know if the plugin is compatible or if there's any plan to support the new version. Thank you!

**Comment by sjelfull** [comment]
Hi! Yeah, I have plans to support Craft 4, but its tricky with finding the time now that I have a boxfresh kid. Happy to take PRs or get paid to upgrade it if it is essential in your project(s) in the mean time.

**Comment by thupsi** [comment]
Oh man, I can totally understand the kid situation: When we had twins some years ago I barelly had time to work at all! Take care of yourself and your family and - when/if you have time - spare some love for the plugin :)

**Comment by sjelfull** [comment]
You can try upgrading by changing your dependency in composer.json to:
```
"require": {
  "superbig/craft-mjml": "dev-v2 as 2.0.0-beta.1",
  "...": "..."
}
```

I didn't really test it, just did a quick pass on code changes, so would be great if you did and gave me any feedback. In theory it should just work.

**Comment by thupsi** [comment]
Thanks for the quick response! 

I just tried it (actually with ```v2.x-dev as 2.0.0-beta.1```), and I managed to complete the upgrade, but my templates throw an exeption with the message ```Unknown "filter" tag```

**Comment by sjelfull** [comment]
I think Craft 4 might have done away with the filter tag - will check

**Comment by thupsi** [comment]
Yay! I just switched from ``filter`` to ``apply`` and it works! 🚀

Thanks again and best wishes for your family!

**Comment by adrienpicard** [comment]
Thanks so much @sjelfull ! 👍

**Comment by sjelfull** [comment]
Updated readme. If everyone is feeling good i'll tag 2.0.0 later today.

**Comment by davidsprinz** [comment]
Can confirm that it seems to work with `v2.x-dev as 2.0.0-beta.1`. Just tested on a clean Craft 4 installation and threw in some of the classic MJML-templates. Thanks a lot, this plugin is a lifesaver. All the best for you and the family!

**Comment by sjelfull** [comment]
Great stuff! 

Alright, [tagged 2.0.0-beta.1](https://github.com/superbigco/craft-mjml/releases/tag/2.0.0-beta.1).

If I hear nothing back I'll tag 2.0.0 proper next week.

**Comment by sjelfull** [comment]
2.0.0 has been released.
