### ISSUE TITLE
New release for Craft 5?

### ISSUE THREAD

**Issue by davidsprinz** [superbigco/craft-mjml#22]
Hi!

Is there's a Craft 5 release planned for your plugin?

Best,
David

**Comment by thupsi** [comment]
I also would like an update on this, thanks!

**Comment by sjelfull** [comment]
I plan to upgrade this to Craft 5, yes. Will update this once it is out.

**Comment by davidsprinz** [comment]
Very glad to hear that!

**Comment by BrandKits** [comment]
My workflow is very reliant on this, so many thanks for updating.

**Comment by DynamiteGoesBoom** [comment]
Is there an ETA for this? Thanks for creating this 🎉

**Comment by sjelfull** [comment]
Likely within a few weeks, might be sooner.

**Comment by sjelfull** [comment]
5.0.0 is out with support for Craft 5 + some fixes.

**Comment by davidsprinz** [comment]
Yeah, thanks a lot! Will try in the next few days.

**Comment by thupsi** [comment]
Awesome! Thanks!
