### ISSUE TITLE
Regression in MJML binary usage with npx, nvm

### ISSUE THREAD

**Issue by soulseekah** [superbigco/craft-mjml#26]
This commit https://github.com/superbigco/craft-mjml/commit/00db9a9048d3ca9d0c3bb024b4be7ab917541a40 introduces a regression and a breaking change in how `mjml` can be (and is) used with `npx` without a global installation, and also introduces friction in nvm-based environments.

We used to be able to just supply the following configuration:

```
MJML_NODE_PATH=npx
MJML_CLI_PATH=mjml    
```

This now throws an exception. And forces us to:

1. Supply the full path to a node binary, which under nvm is based on the current user directory and node version installed, which will change with node updates and across users (for example: `/home/$HOME/.nvm/versions/node/v$VERSION/bin/node`).
2. Install mjml globally or under nvm, or supply the node_modules path, which also changes (see 1.)

This severely limits a flexible setup with non-globally installation of mjml and node, and breaks usage via npx altogether.

Broken via https://github.com/superbigco/craft-mjml/issues/20

Code that breaks with `file_exists` https://github.com/superbigco/craft-mjml/commit/00db9a9048d3ca9d0c3bb024b4be7ab917541a40#diff-1639e3c1b104889ebfbeb509353e2334602ecad5d689941359b4166f2ff6720cR147-R156.

There are several approaches in fixing this and I'm available to help solve this.

One of the easier ways, I believe, is to check all `PATH=` environment variables that are passed onto PHP to find the binaries. If `npx` is the binary, the mjml path should not be checked with `file_exists`.

**Comment by Romanavr** [comment]
Just encountered the same issue.
Please fix ASAP⚡

**Comment by sjelfull** [comment]
@soulseekah Ah, thanks for opening this. Of course this broke npx and I assume `pnpm dlx` as well. Would you mind opening a PR? I'm heading on vacation next week and won't have much time in a while for this.

**Comment by soulseekah** [comment]
> @soulseekah Ah, thanks for opening this. Of course this broke npx and I assume `pnpm dlx` as well. Would you mind opening a PR? I'm heading on vacation next week and won't have much time in a while for this.

@sjelfull thanks for your support. PR is opened, hopefully we can polish and fine-tune the approach before your vacation and have a minor release ;)

**Comment by vadimgodev** [comment]
Waiting for the PR, need it asap

**Comment by sjelfull** [comment]
Thanks, new release tagged!

**Comment by daniellelecomte** [comment]
@sjelfull - can this fix also be rolled into the Craft 4 version?
